# Project 4 - Books Recommendation using SVD
Collaborative based filtering->Item based

In [1]:
# !pip install scikit-surprise

# Import Dependencies

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from surprise import accuracy, Dataset, Reader, SVD, BaselineOnly, PredictionImpossible
from surprise.model_selection import train_test_split, cross_validate, KFold, GridSearchCV
import random
import numpy as np
import statistics as st

# Explore the data

In [3]:
#Creating dataframes from csv files to read the data
books_df_original = pd.read_csv('./Resources/Books.csv')
users_df = pd.read_csv('./Resources/Users.csv')
ratings_df_original = pd.read_csv('./Resources/Ratings.csv')

/var/folders/3g/t4y_09d901v7s2qw9dqk8jzw0000gn/T/ipykernel_443/570273266.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_df_original = pd.read_csv('./Resources/Books.csv')

In [4]:
# Filter out data with no publication year
books_df = books_df_original[books_df_original['Year-Of-Publication'] != 0]

In [5]:
# remove duplicated books records if any by looking at ISBN
books_df=books_df.drop_duplicates(subset=['ISBN'])

In [6]:
books_df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 267790 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 267790 non-null  object
 1   Book-Title           267790 non-null  object
 2   Book-Author          267788 non-null  object
 3   Year-Of-Publication  267790 non-null  object
 4   Publisher            267788 non-null  object
 5   Image-URL-S          267790 non-null  object
 6   Image-URL-M          267790 non-null  object
 7   Image-URL-L          267787 non-null  object
dtypes: object(8)
memory usage: 18.4+ MB

In [8]:
duplicated_titles=books_df[books_df.duplicated(subset=['Book-Title'],keep=False)].sort_values(by='Book-Title')
duplicated_titles.head()
# ????????how to handle those duplicates???????? drop those with earlier year of publication

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
75637,1565920465,!%@ (A Nutshell handbook),Donnalyn Frey,1994,O'Reilly,http://images.amazon.com/images/P/1565920465.0...,http://images.amazon.com/images/P/1565920465.0...,http://images.amazon.com/images/P/1565920465.0...
156341,1565920317,!%@ (A Nutshell handbook),Donnalyn Frey,1993,O'Reilly,http://images.amazon.com/images/P/1565920317.0...,http://images.amazon.com/images/P/1565920317.0...,http://images.amazon.com/images/P/1565920317.0...
140618,0792276833,'A Hell of a Place to Lose a Cow': An American...,Tim Brookes,2000,National Geographic,http://images.amazon.com/images/P/0792276833.0...,http://images.amazon.com/images/P/0792276833.0...,http://images.amazon.com/images/P/0792276833.0...
158204,0792277295,'A Hell of a Place to Lose a Cow': An American...,Tim Brookes,2001,National Geographic,http://images.amazon.com/images/P/0792277295.0...,http://images.amazon.com/images/P/0792277295.0...,http://images.amazon.com/images/P/0792277295.0...
10438,0451168089,'Salem's Lot,Stephen King,1990,Signet Book,http://images.amazon.com/images/P/0451168089.0...,http://images.amazon.com/images/P/0451168089.0...,http://images.amazon.com/images/P/0451168089.0...

In [9]:
ratings_df=ratings_df_original.copy()
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [10]:
# update the datatype of a 'Book-Rating' field to numeric one
ratings_df['Book-Rating']=pd.to_numeric(ratings_df['Book-Rating'],errors='coerce')
# and check the result
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [11]:
############## users with solid number of reviews shortens a lot!
# find the list of ISBN that we have book info for them
isbn=books_df['ISBN'].unique()

# adjust ratings  dataframe to match with those books
ratings_df=ratings_df[ratings_df['ISBN'].isin(isbn)]
############## users with solid number of reviews shortens a lot!

In [12]:
#check for n/a values
ratings_df[ratings_df['Book-Rating'].isna()|ratings_df['ISBN'].isna()|ratings_df['User-ID'].isna()]

Empty DataFrame
Columns: [User-ID, ISBN, Book-Rating]
Index: []

In [13]:
# drop rows with N/As if any
ratings_df=ratings_df[~(ratings_df['Book-Rating'].isna()|ratings_df['ISBN'].isna()|ratings_df['User-ID'].isna())]
ratings_df

         User-ID        ISBN  Book-Rating
0         276725  034545104X            0
1         276726  0155061224            5
2         276727  0446520802            0
3         276729  052165615X            3
4         276729  0521795028            6
...          ...         ...          ...
1149774   276704  0876044011            0
1149775   276704  1563526298            9
1149776   276706  0679447156            0
1149777   276709  0515107662           10
1149778   276721  0590442449           10

[1018392 rows x 3 columns]

In [14]:
# Check distribution by scores 
groupped_r_scores=ratings_df.groupby(['Book-Rating']).size()
groupped_r_scores

Book-Rating
0     639805
1       1461
2       2339
3       5040
4       7504
5      44793
6      31236
7      65439
8      90494
9      59965
10     70316
dtype: int64

#### Update 0 scores with weighted averages

In [16]:
avg_ratings_scored = ratings_df[ratings_df['Book-Rating'] > 0].groupby('ISBN')['Book-Rating'].mean()
avg_ratings_scored

ISBN
0000913154     8.0
000104687X     6.0
0001047213     9.0
0001047973     9.0
000104799X     7.5
              ...
B0001FZGPI     7.0
B0001FZGRQ     9.0
B0001GMSV2     8.0
B0001I1KOG    10.0
B000234N3A     9.0
Name: Book-Rating, Length: 147598, dtype: float64

In [17]:
count_ratings_scored = ratings_df[ratings_df['Book-Rating'] > 0].groupby('ISBN')['Book-Rating'].count()
count_ratings_scored

ISBN
0000913154    1
000104687X    1
0001047213    1
0001047973    2
000104799X    2
             ..
B0001FZGPI    1
B0001FZGRQ    1
B0001GMSV2    2
B0001I1KOG    1
B000234N3A    1
Name: Book-Rating, Length: 147598, dtype: int64

In [18]:
average_weighted_df=pd.DataFrame(avg_ratings_scored).rename(columns={'Book-Rating':'avg_book_rating'})
count_ratings_scored_df=pd.DataFrame(count_ratings_scored).rename(columns={'Book-Rating':'count_book_rating'})
average_weighted_df=pd.merge(average_weighted_df,count_ratings_scored_df,  on='ISBN', how='inner')
average_weighted_df=average_weighted_df.sort_values(by='count_book_rating', ascending=False)
average_weighted_df.head()

            avg_book_rating  count_book_rating
ISBN
0316666343         8.185290                707
0971880107         4.390706                581
0385504209         8.435318                487
0312195516         8.182768                383
0060928336         7.887500                320

In [19]:
def average_weighted(row):
    min_th=25 #min number of rating received by the book
    neutral_score=5
    avg_w = ((row['avg_book_rating'] * row['count_book_rating']) + 
      (min_th * neutral_score))/(row['count_book_rating'] + min_th)
    return avg_w

In [20]:
average_weighted_df['avg_weighted']=average_weighted_df.apply(average_weighted, axis=1)
average_weighted_df

            avg_book_rating  count_book_rating  avg_weighted
ISBN
0316666343         8.185290                707      8.076503
0971880107         4.390706                581      4.415842
0385504209         8.435318                487      8.267578
0312195516         8.182768                383      7.987745
0060928336         7.887500                320      7.678261
...                     ...                ...           ...
0553013769         5.000000                  1      5.000000
0553013653         8.000000                  1      5.115385
0553013602         5.000000                  1      5.000000
0553013394         6.000000                  1      5.038462
B000234N3A         9.000000                  1      5.153846

[147598 rows x 3 columns]

In [21]:
ratings_df_adj=ratings_df.copy()

In [22]:
ratings_df_adj=ratings_df_adj.set_index('ISBN')
ratings_df_adj

            User-ID  Book-Rating
ISBN
034545104X   276725            0
0155061224   276726            5
0446520802   276727            0
052165615X   276729            3
0521795028   276729            6
...             ...          ...
0876044011   276704            0
1563526298   276704            9
0679447156   276706            0
0515107662   276709           10
0590442449   276721           10

[1018392 rows x 2 columns]

In [23]:
ratings_df_adj.loc[ratings_df_adj['Book-Rating'] == 0, 'Book-Rating'] = ratings_df_adj.loc[ratings_df_adj['Book-Rating'] == 0].index.map(average_weighted_df['avg_weighted'])
ratings_df_adj

            User-ID  Book-Rating
ISBN
034545104X   276725     5.679245
0155061224   276726     5.000000
0446520802   276727     7.358025
052165615X   276729     3.000000
0521795028   276729     6.000000
...             ...          ...
0876044011   276704          NaN
1563526298   276704     9.000000
0679447156   276706     6.050000
0515107662   276709    10.000000
0590442449   276721    10.000000

[1018392 rows x 2 columns]

In [24]:
# Filter out data with n/a rating score after mapping, as there could be books with only 0 scores
ratings_df_adj=ratings_df_adj.dropna(subset=['Book-Rating'])
ratings_df_adj

            User-ID  Book-Rating
ISBN
034545104X   276725     5.679245
0155061224   276726     5.000000
0446520802   276727     7.358025
052165615X   276729     3.000000
0521795028   276729     6.000000
...             ...          ...
0806917695   276704     5.000000
1563526298   276704     9.000000
0679447156   276706     6.050000
0515107662   276709    10.000000
0590442449   276721    10.000000

[840848 rows x 2 columns]

In [25]:
ratings_df_adj['Book-Rating']=round(ratings_df_adj['Book-Rating'],0)
ratings_df_adj.head()

/var/folders/3g/t4y_09d901v7s2qw9dqk8jzw0000gn/T/ipykernel_443/3694924668.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings_df_adj['Book-Rating']=round(ratings_df_adj['Book-Rating'],0)

            User-ID  Book-Rating
ISBN
034545104X   276725          6.0
0155061224   276726          5.0
0446520802   276727          7.0
052165615X   276729          3.0
0521795028   276729          6.0

# Train the model

# Training: data preparation

In [27]:
# Change ISBN with Titles
# Merge ratings with books data in order to change isbn with title and leave only those ratings data for which we have title info
ratings_df_adj=pd.merge(books_df,ratings_df_adj,on='ISBN', how = 'inner')
ratings_df_adj=ratings_df_adj.drop(['ISBN','Book-Author','Year-Of-Publication','Publisher','Image-URL-S','Image-URL-M','Image-URL-L'], axis=1)
ratings_df_adj=ratings_df_adj.dropna()
ratings_df_adj

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400,6.0
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8.0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385,6.0
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,67544,8.0
...,...,...,...,...,...,...,...,...,...,...
840843,0395264707,Dreamsnake,Vonda N. McIntyre,1978,Houghton Mifflin,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,275318,10.0
840844,1845170423,Cocktail Classics,David Biggs,2004,Connaught,http://images.amazon.com/images/P/1845170423.0...,http://images.amazon.com/images/P/1845170423.0...,http://images.amazon.com/images/P/1845170423.0...,275970,7.0
840845,0449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,276313,5.0
840846,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,276463,7.0
840847,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,276579,4.0

In [30]:
# check if there are duplicated records when same user rated book(s) with same title several times
ratings_df_adj[ratings_df_adj.duplicated(subset=['Book-Title', 'User-ID'],keep=False)].sort_values(by=['Book-Title','User-ID'])

                 Book-Title  User-ID  Book-Rating
478255       10 Lb. Penalty    94923          5.0
574558       10 Lb. Penalty    94923          6.0
478259       10 Lb. Penalty   128835          5.0
574562       10 Lb. Penalty   128835          9.0
478264       10 Lb. Penalty   198711          5.0
...                     ...      ...          ...
275040  \O\" Is for Outlaw"   155147          7.0
106005  \O\" Is for Outlaw"   158295          7.0
275043  \O\" Is for Outlaw"   158295          6.0
106030  \O\" Is for Outlaw"   196077          7.0
275054  \O\" Is for Outlaw"   196077          7.0

[7895 rows x 3 columns]

In [31]:
# Use avg rate per duplicates set
ratings_df_adj=ratings_df_adj.groupby(['Book-Title','User-ID'])['Book-Rating'].mean().reset_index()
ratings_df_adj

                                           Book-Title  User-ID  Book-Rating
0                                        Clara Callan        8          5.0
1                                        Clara Callan    11400          6.0
2                                        Clara Callan    11676          8.0
3                                        Clara Callan    41385          6.0
4                                        Clara Callan    67544          8.0
...                                               ...      ...          ...
840843                                     Dreamsnake   275318         10.0
840844                              Cocktail Classics   275970          7.0
840845  Flashpoints: Promise and Peril in a New World   276313          5.0
840846                     There's a Bat in Bunk Five   276463          7.0
840847                        From One to One Hundred   276579          4.0

[839239 rows x 3 columns]

### Only leave statistically signifacant data

In [33]:
# Define whar are the number of rates per book and books rated by user we treat as statistically significant
min_books_rated_by_user=5
min_rates_received_by_book=5

In [34]:
groupped_r_users=ratings_df_adj.groupby('User-ID')['Book-Rating'].count()
groupped_r_users[:5]

User-ID
8     14
9      3
10     1
12     1
14     4
Name: Book-Rating, dtype: int64

In [35]:
groupped_r_books=ratings_df_adj.groupby('Book-Title')['User-ID'].count()
groupped_r_books[:5]

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)     4
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                          1
 Dark Justice                                                                                                  1
 Earth Prayers From around the World: 365 Prayers, Poems, and Invocations for Honoring the Earth              10
 Final Fantasy Anthology: Official Strategy Guide (Brady Games)                                                4
Name: User-ID, dtype: int64

In [36]:
#select only those books which were rated more than min_rates_received_by_book
titles_with_acceptable_rates_count=list(groupped_r_books[groupped_r_books>min_rates_received_by_book].index)
titles_with_acceptable_rates_count[:5]

[' Earth Prayers From around the World: 365 Prayers, Poems, and Invocations for Honoring the Earth',
 ' Good Wives: Image and Reality in the Lives of Women in Northern New England, 1650-1750',
 ' Goosebumps Monster Edition 1: Welcome to Dead House, Stay Out of the Basement, and Say Cheese and Die!',
 ' Murder of a Sleeping Beauty (Scumble River Mysteries (Paperback))',
 ' Q-Space (Star Trek The Next Generation, Book 47)']

In [37]:
#select only those users (user_id) who rated more than min_books_rated_by_user books
user_ids_with_acceptable_books_count_rated=list(groupped_r_users[groupped_r_users>min_books_rated_by_user].index)
user_ids_with_acceptable_books_count_rated[:5]

[8, 17, 99, 114, 242]

In [38]:
# filter rating-user data to have only books/users of interest (which have highest rates count and rated highest number of books respectively)
rating_input_df=ratings_df_adj[ratings_df_adj['Book-Title'].isin(titles_with_acceptable_rates_count)&ratings_df_adj['User-ID'].isin(user_ids_with_acceptable_books_count_rated)]
rating_input_df

                                            Book-Title  User-ID  Book-Rating
0                                         Clara Callan        8          5.0
1                                         Clara Callan    11400          6.0
2                                         Clara Callan    11676          8.0
3                                         Clara Callan    41385          6.0
4                                         Clara Callan    67544          8.0
...                                                ...      ...          ...
840606                                Hush Little Baby   245088          8.0
840711                    The Twelve Days of Christmas   252676         10.0
840777  The Two Towers (The Lord of the Rings, Part 2)   259901         10.0
840843                                      Dreamsnake   275318         10.0
840846                      There's a Bat in Bunk Five   276463          7.0

[551099 rows x 3 columns]

### Prepare data for parsing by 'surprise algorithms'

In [39]:
# Even having dataframe we need to create a 'reader' with the 'rating_scale' parameter to let know that our dataset has ratings from 1 to 10
# https://surprise.readthedocs.io/en/stable/getting_started.html#load-custom
reader = Reader(rating_scale=(1,10))

# and create respective surprise.dataset object, so that our data are in a proper format for the recommendation algorithms
data_surprise_o = Dataset.load_from_df(rating_input_df[['User-ID','Book-Title','Book-Rating']], reader)

data_surprise_o

#### Split our data into train and test in ratio 8:2
Use random_state = 42 so that we receive reproducable output

In [40]:
random_state = 42

In [41]:
# Option1:
# Reference: https://surprise.readthedocs.io/en/stable/getting_started.html?highlight=train_test_split#train-test-split-and-the-fit-method

train_set, test_set = train_test_split(data_surprise_o, test_size=0.2, shuffle=True, random_state=random_state)

train_data = list(train_set.all_ratings())

print(f'Size of train_set: {len(train_data)}')
print(f'Number of users in train_set: {train_set.n_users}')
print(f'Number of books in train_set: {train_set.n_items}')

train_set

Size of train_set: 440879
Number of users in train_set: 16053
Number of books in train_set: 28539

In [42]:
train_set.all_items()

range(0, 28539)

In [43]:
# Option2:
# reference: https://datascience.stackexchange.com/questions/73583/how-to-train-test-split-and-cross-validate-in-surprise
# get already parsed data in its raw form
# check here for raw vs inner https://surprise.readthedocs.io/en/stable/FAQ.html#what-are-raw-and-inner-ids
train_dataset_obj = Dataset.load_from_df(rating_input_df[['User-ID','Book-Title','Book-Rating']], reader) # we kind of copying the original dataset
raw_data = train_dataset_obj.raw_ratings

# shuffle ratings to ensure that the data is randomized
np.random.seed(random_state)
np.random.shuffle(raw_data)
display (f'Size of raw_data: {len(raw_data)}')
display(f'Few elements of raw_data: {raw_data[:5]}')

#???????????????
# WHY DO WE HAVE 'None' here as 4-th element?
#???????????????

'Size of raw_data: 551099'

'Few elements of raw_data: [(153723, \'Kiss Me, Cowboy!\', 7.0, None), (163128, \'Caribbean\', 7.0, None), (264996, "The Death of Innocence : The Untold Story of JonBenet\'s Murder and How Its Exploitation Compromised the Pursuit of Truth", 6.0, None), (16916, \'Welcome to the World, Baby Girl!\', 7.0, None), (59172, \'Firefly\', 5.0, None)]'

In [44]:
# find the lenght of train set having it should be 80% of all data
train_lenght = int(0.8 * len(raw_data))
# split the whole set of raw data into train and test one
train_part_raw = raw_data[:train_lenght]
test_part_raw = raw_data[train_lenght:]

# create respective train object and test set
train_dataset_obj.raw_ratings=train_part_raw  #trick to receive a dataset object from raw data 'train_part_raw'
train_set = train_dataset_obj.build_full_trainset()
test_set = train_dataset_obj.construct_testset(test_part_raw)
print(f'Type of train_set: {type(train_set)}')
print(f'Type of test_set: {type(test_set)}')

Type of train_set: <class 'surprise.trainset.Trainset'>
Type of test_set: <class 'list'>

In [45]:
# check train and test data
train_data = list(train_set.all_ratings())

display('------Train Set------')
print(f'Size of train_set: {len(train_data)}')
print(f'Number of users in train_set: {train_set.n_users}')
print(f'Number of books in train_set: {train_set.n_items}')
display(f'Few elements of train_set (user, book, rating): {train_data[:15]}')
display('------Test Set------')
print(f'Size of test_set: {len(test_set)}')
display(f'Few elements of test_set (user, book, rating): {test_set[:15]}')

'------Train Set------'

Size of train_set: 440879
Number of users in train_set: 16053
Number of books in train_set: 28539

'Few elements of train_set (user, book, rating): [(0, 0, 7.0), (0, 895, 5.0), (0, 2181, 6.0), (0, 11031, 5.0), (0, 12833, 5.0), (0, 11873, 5.0), (0, 8019, 7.0), (0, 5643, 5.0), (0, 15765, 5.0), (0, 316, 7.0), (0, 23358, 5.0), (0, 24214, 5.0), (0, 3926, 7.0), (0, 4802, 7.0), (0, 23272, 6.0)]'

'------Test Set------'

Size of test_set: 110220

"Few elements of test_set (user, book, rating): [(52584, 'DEATH PERFECT MOTHER', 5.0), (220867, 'Driving over Lemons: An Optimist in Spain (Vintage Departures)', 6.0), (102967, 'Shadowfires', 6.0), (265313, 'Riptide', 6.0), (153662, 'The Majors (Brotherhood of War)', 5.0), (235173, 'The Fig Eater : A Novel', 6.0), (269352, 'A Clockwork Orange (Norton Paperback Fiction)', 10.0), (158295, 'Junie B. Jones Is a Graduation Girl', 5.0), (87707, 'Le Grand Secret', 7.0), (244428, 'These High, Green Hills (The Mitford Years)', 7.0), (20995, 'The Cobra Event', 10.0), (252392, 'One Flew Over the Cuckoos Nest', 10.0), (258185, 'Beautiful Dreamer', 5.0), (162639, 'The Miss America Family : A Novel', 5.0), (131046, 'Making over Mike (Regency Contemporary Romance)', 5.0)]"

In [46]:
# not really sure I understand the difference here between options (in general it's stated that the second one works if we want to cross validate)
# can we receive more input here?????

## Training: cross validate the model
Make preliminary estimation of error in predictions using RMSE metric for SVD() model and the whole set of data split into 5 folds

In [65]:
# reference: https://surprise.readthedocs.io/en/stable/getting_started.html?highlight=cross_validate#use-cross-validation-iterators

# define number of subsets the dataset will be partitioned for cross validations
folds_n=5

# define a cross-validation iterator
kf = KFold(n_splits=folds_n,random_state=42)

algo = [BaselineOnly(),SVD()]

for i in algo:
    mean_rmse=[]
    for trainset, testset in kf.split(data_surprise_o):

        # train and test algorithm.
        i.fit(trainset)
        predictions = i.test(testset)

        # Compute and print Root Mean Squared Error
        mean_rmse.append(accuracy.rmse(predictions))

    # Find an average rmse for all the folds
    mean_rmse=st.mean(mean_rmse)
    display(f'Average Root Mean Square Error (RMSE) for {i.__class__.__name__} is {round(mean_rmse,2)}')

Estimating biases using als...
RMSE: 1.2912
Estimating biases using als...
RMSE: 1.2903
Estimating biases using als...
RMSE: 1.2905
Estimating biases using als...
RMSE: 1.2875
Estimating biases using als...
RMSE: 1.2877

'Average Root Mean Square Error (RMSE) for BaselineOnly is 1.29'

RMSE: 1.3087
RMSE: 1.3047
RMSE: 1.3069
RMSE: 1.3029
RMSE: 1.3043

'Average Root Mean Square Error (RMSE) for SVD is 1.31'

## Training: identify best parameters

In [48]:
# # reference: https://medium.com/p/61c269402919
# # within the dictionary param_grid set ranges for parameters to try out, where 
# #  - key: parameter name, 
# #  - value:  list of parameter values to try
# param_grid = {'n_factors':[10,20,50,100,150], 'n_epochs':[10,20,30,50, 100], 'lr_all':[0.002,0.005,0.01,0.3],'reg_all':[0.02, 0.1, 0.2]}
# # n_factors - number of latent factors (Default is 100)
# # n_epochs - number of iterations (Default is 20)
# # lr_all - step size for the gradient descent optimization (learning rate, Default is 0.005)
# # reg_all -  regularization term for all parameter, used to prevent overfitting (Default is 0.02)

# # Select parameters for our SVD algorithm by cross validation and looking for rmse metric
# # GridSearchCV() calculates a score for each combination of hyperparameters on a k-fold cross validated dataset 
# # and returns the set of parameters that minimises the mean score across folds
# gs = GridSearchCV(SVD, param_grid, measures=['rmse'], cv=5)

# # train the model for all the combinations of parameters
# gs.fit(data_surprise_o)

# # select the set of parameters that produce lowest value for rmse metric
# params = gs.best_params['rmse']

# params

## Training: Build models

In [49]:
# Build SVD with default parameters
svd_default = SVD()

In [50]:
# Build SVD, using hyperparameters recevied in the result of hypertuning
# svd_best_parameters = SVD(n_factors=params['n_factors'], n_epochs=params['n_epochs'],lr_all=params['lr_all'], reg_all=params['reg_all'])

In [51]:
# TO DELETE IN CASE WE RUN PARAMETERS TUNING
svd_best_parameters=svd_default
# TO DELETE IN CASE WE RUN PARAMETERS TUNING

## Training: Fit models

In [52]:
# Train the models on trainset
svd_best_parameters_model = svd_best_parameters.fit(train_set)
svd_default_model = svd_default.fit(train_set)

# Recommendation generation

In [53]:
# Define the number of books to recommend by algorithm
recommendations_count=5

### Find list of books (titles) among which recommendations will be selected

In [54]:
# let us select dummy user   e.g. 25919, 
user_id=6251

# find all the books (titles) in ratings_df. 
# Note, this only include those books which both: 
# (1) were rated at least min_rates_received_by_book times by users, who rated at least min_books_rated_by_user
# and (2) we have titles for those books
# ??????????We may need to remove (1) condition and look for books, which were rated at least once??????????
all_titles=ratings_df_adj['Book-Title'].unique()
all_titles

# find the books (titles) that were rated and presumably read by a user
rated_titles=[i for i in ratings_df_adj.loc[ratings_df_adj['User-ID']==user_id,'Book-Title']]
rated_titles


# find the books (titles) that were not rated and presumably not read by a user
titles_input_to_recommend=[i for i in all_titles if i not in rated_titles]
titles_input_to_recommend[:5]

['Clara Callan',
 'Decision in Normandy',
 'Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It',
 "What If?: The World's Foremost Military Historians Imagine What Might Have Been",
 'PLEADING GUILTY']

In [55]:
rated_book_title_rate =[(row['Book-Title'],row['Book-Rating']) for i,row in ratings_df_adj[ratings_df_adj['User-ID']==user_id].iterrows()]
rated_book_title_rate

[('Wild Animus', 4.0),
 ('Timeline', 8.0),
 ('Isle of Dogs', 5.0),
 ('A Soldier of the Great War', 7.0),
 ('The Joy Luck Club', 8.0),
 ('The Tao of Pooh', 10.0),
 ('Seabiscuit', 7.0),
 ("Life's Little Instruction Book (Life's Little Instruction Books (Paperback))",
  7.0),
 ('Starship Troopers', 7.0),
 ("Corelli's Mandolin : A Novel", 7.0),
 ('The Five People You Meet in Heaven', 8.0),
 ('The Sum of All Fears', 7.0),
 ('Little Altars Everywhere: A Novel', 7.0),
 ('Body of Evidence (Kay Scarpetta Mysteries (Paperback))', 7.0),
 ('The Rescue', 7.0),
 ("The Kalahari Typing School for Men (No. 1 Ladies' Detective Agency)", 7.0),
 ('Wicked: The Life and Times of the Wicked Witch of the West', 7.0),
 ('Lies and the Lying Liars Who Tell Them: A Fair and Balanced Look at the Right',
  8.0),
 ("On the Bright Side, I'm Now the Girlfriend of a Sex God: Further Confessions of Georgia Nicolson",
  6.0),
 ('Eva Luna', 7.0),
 ('A Man in Full', 6.0),
 ("Vinegar Hill (Oprah's Book Club (Paperback))", 6.0),
 ('Bel Canto', 7.0),
 ('Lakota Woman', 6.0),
 ('The Perfect Storm : A True Story of Men Against the Sea', 7.0),
 ('Hannibal', 6.0),
 ('Cavedweller', 6.0),
 ('The Firm', 8.0),
 ('The Scarlet Letter', 7.0),
 ("She's Come Undone (Oprah's Book Club)", 7.0),
 ('Nickel and Dimed: On (Not) Getting By in America', 8.0),
 ('The Diary of Ellen Rimbauer: My Life at Rose Red', 6.0),
 ('Be Cool', 5.0),
 ('The Bean Trees', 8.0),
 ('Daughter of Fortune', 7.0),
 ('The Red Tent (Bestselling Backlist)', 8.0),
 ('The Nanny Diaries: A Novel', 7.0),
 ('Everything Is Illuminated: A Novel', 6.0),
 ('Prince Caspian', 6.0),
 ("Angela's Ashes: A Memoir", 8.0),
 ('Fast Food Nation: The Dark Side of the All-American Meal', 8.0),
 ('One for the Money (Stephanie Plum Novels (Paperback))', 7.0),
 ("Where the Heart Is (Oprah's Book Club (Paperback))", 8.0),
 ("The Girls' Guide to Hunting and Fishing", 7.0),
 ('Blackbird: A Childhood Lost and Found', 7.0),
 ('Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
  7.0),
 ('All the Pretty Horses (Border Trilogy, Vol 1)', 6.0),
 ('The Bad Beginning (A Series of Unfortunate Events, Book 1)', 7.0),
 ('About a Boy (Movie Tie-In)', 7.0),
 ("Smilla's Sense of Snow", 6.0),
 ("The Magician's Nephew (Narnia)", 8.0),
 ('The Phantom Tollbooth', 10.0),
 ('SHIPPING NEWS', 7.0),
 ('Reap the Wind', 7.0),
 ('Frankenstein Or, the Modern Prometheus', 6.0),
 ('American Gods', 7.0),
 ('Tales of the City (Tales of the City Series, V. 1)', 7.0),
 ('Red Dragon', 7.0),
 ('Jurassic Park', 8.0),
 ('The God of Small Things', 6.0),
 ('Mother of Pearl', 6.0),
 ("Lamb : The Gospel According to Biff, Christ's Childhood Pal", 10.0),
 ('Nickel and Dimed: On (Not) Getting By in America', 7.0),
 ('Good Omens', 10.0),
 ('The Poisonwood Bible: A Novel', 8.0),
 ("Operating Instructions: A Journal of My Son's First Year", 7.0),
 ('Jewel', 7.0),
 ('The Prophet', 10.0),
 ("The No. 1 Ladies' Detective Agency (Today Show Book Club #8)", 8.0),
 ('Shopgirl', 8.0),
 ('The Devil in the White City : Murder, Magic, and Madness at the Fair That Changed America (Illinois)',
  7.0),
 ("The Kitchen God's Wife", 7.0),
 ("Songs in Ordinary Time (Oprah's Book Club (Paperback))", 6.0),
 ('Good in Bed', 8.0),
 ('Out of Sight', 6.0),
 ('How to Make an American Quilt', 6.0),
 ('The Years of Rice and Salt', 6.0),
 ('A Heartbreaking Work of Staggering Genius', 4.0),
 ('The Eyre Affair (Alex Awards (Awards))', 7.0),
 ('A Year in Provence', 7.0),
 ('The Indian in the Cupboard', 10.0),
 ('What to Expect the First Year', 7.0),
 ('The Partner', 7.0),
 ('The Alienist', 7.0),
 ('The Smoke Jumper', 7.0),
 ("The Ultimate Hitchhiker's Guide", 10.0),
 ('To Cut a Long Story Short', 6.0),
 ('Fg on Our Immigrant Ance', 10.0),
 ('Fg Cooks American', 9.0),
 ('Into Thin Air : A Personal Account of the Mt. Everest Disaster', 8.0),
 ('Snow Falling on Cedars', 8.0),
 ('Leaving Home', 9.0),
 ('The Lost World', 7.0),
 ("The Shelters of Stone (Earth's Children Series, No 5)", 3.0),
 ("A Room of One's Own", 6.0),
 ('Lucky You', 6.0),
 ("CAT'S EYE", 6.0),
 ("The Handmaid's Tale", 8.0),
 ('White Oleander : A Novel', 8.0),
 ('Out to Canaan (The Mitford Years)', 6.0),
 ('These High, Green Hills (The Mitford Years)', 8.0),
 ('A Light in the Window (The Mitford Years)', 7.0),
 ("Reviving Ophelia: Saving the Selves of Adolescent Girls (Ballantine Reader's Circle)",
  8.0),
 ("Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))", 9.0),
 ('Skinny Legs and All', 7.0),
 ("Ender's Game (Ender Wiggins Saga (Paperback))", 8.0),
 ("Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
  7.0),
 ('Mystic River', 7.0),
 ('Sick Puppy', 7.0),
 ('One', 6.0),
 ('Babyhood', 7.0),
 ('Interview with the Vampire', 8.0),
 ('The Queen of the Damned (Vampire Chronicles (Paperback))', 7.0),
 ('A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
  7.0),
 ('Reading Lolita in Tehran: A Memoir in Books', 7.0),
 ('How to Talk So Kids Will Listen and Listen So Kids Will Talk', 6.0),
 ('The Visitor (Animorphs, No 2)', 6.0),
 ('Standing in the Rainbow', 7.0),
 ('Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
  10.0),
 ("Dude, Where's My Country?", 10.0),
 ('Homecoming', 6.0),
 ('The Tale of the Body Thief (Vampire Chronicles (Paperback))', 7.0),
 ('Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))', 7.0),
 ('The Hours: A Novel', 7.0),
 ('Carrie Pilby (Red Dress Ink (Paperback))', 6.0),
 ('Behind the Scenes at the Museum : A Novel', 6.0),
 ('Follow the River', 6.0),
 ('The Runaway Jury', 7.0),
 ('The Experiment (Animorphs, No 28)', 5.0),
 ('The Mambo Kings Play Songs of Love', 6.0),
 ('Harry Potter and the Chamber of Secrets (Book 2)', 8.0),
 ('The Curious Incident of the Dog in the Night-Time (Vintage Contemporaries)',
  10.0),
 ('Sula', 6.0),
 ('The Kite Runner (Alex Awards (Awards))', 6.0),
 ('A BEAUTIFUL MIND: A Biography of John Forbes Nash, Jr., Winner of the Nobel Prize in Economics, 1994',
  6.0),
 ('Island of the Sequined L', 8.0),
 ('The King Must Die', 6.0),
 ('The Autobiography of Miss Jane Pittman', 5.0),
 ('Basket Case', 7.0),
 ('4 Blondes', 5.0),
 ('Night', 8.0),
 ("Winter's Tale", 10.0),
 ('The Cat in the Hat', 10.0),
 ('Harry Potter and the Prisoner of Azkaban (Book 3)', 10.0),
 ('Battlefield Earth: A Saga of the Year 3000', 6.0),
 ('Primary Colors: A Novel of Politics', 6.0),
 ('American Fuji', 6.0),
 ('Yukon Ho!', 10.0),
 ('Eat Mangoes Naked : Finding Pleasure Everywhere (and dancing with the Pits)',
  8.0),
 ('Transformation Soup : Healing for the Splendidly Imperfect', 6.0),
 ('K Is for Killer (Kinsey Millhone Mysteries (Paperback))', 7.0),
 ('The Bourne Identity', 7.0),
 ('Cat in the Hat (I Can Read It All by Myself Beginner Books)', 6.0),
 ("The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))",
  7.0),
 ('Confessions of a Failed Southern Lady', 6.0),
 ("Charlotte's Web", 7.0),
 ('Mrs Dalloway', 6.0),
 ("White Oleander : A Novel (Oprah's Book Club)", 7.0),
 ('A Widow for One Year : A Novel', 6.0),
 ('Running with Scissors', 6.0),
 ('Confessions of an Ugly Stepsister : A Novel', 7.0),
 ('Zen and the Art of Motorcycle Maintenance: An Inquiry into Values', 7.0),
 ('Stardust', 7.0),
 ('Dying for Chocolate (Culinary Mysteries (Paperback))', 7.0),
 ('Lucky You', 8.0),
 ('Pagan Babies', 6.0),
 ('Prime Cut', 6.0),
 ("The Girls' Guide to Hunting and Fishing", 6.0),
 ('The Pleasure of My Company: A Novel', 10.0),
 ('House of Sand and Fog', 6.0),
 ('The Hot Zone', 7.0),
 ('Nerd in Shining Armor', 6.0),
 ('The Reptile Room (A Series of Unfortunate Events, Book 2)', 7.0),
 ('The Corrections', 6.0),
 ('A Case of Need', 6.0),
 ('The Devil Wears Prada : A Novel', 6.0),
 ('All the Trouble in the World: The Lighter Side of Overpopulation, Famine, Ecological Disaster, Ethnic Hatred, Plague, and Poverty',
  5.0),
 ('A Book Without Covers', 6.0),
 ('The Tenth Justice', 6.0),
 ('East of Eden', 6.0),
 ('All I Really Need to Know', 7.0),
 ('Plague Dogs', 6.0),
 ('Harry Potter and the Goblet of Fire (Book 4)', 10.0),
 ('Redwall (Redwall, Book 1)', 7.0),
 ('Harry Potter and the Order of the Phoenix (Book 5)', 9.0),
 ('Insomnia', 7.0),
 ('Tears of the Giraffe (No.1 Ladies Detective Agency)', 8.0),
 ('Holes (Yearling Newbery)', 8.0),
 ('Time Flies', 6.0),
 ("It's Not About the Bike: My Journey Back to Life", 7.0),
 ('The Blind Assassin', 7.0),
 ('The Butter Did It : A Gastronomic Tale of Love and Murder (Chas Wheatley Mysteries)',
  5.0),
 ('Plainsong', 6.0),
 ('Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
  9.0),
 ('A Short Guide to a Happy Life', 7.0),
 ('Two for the Dough', 8.0),
 ('Bless Me, Ultima', 6.0),
 ('The Emperor of Ocean Park (Today Show Book Club #1)', 7.0),
 ("The Bonesetter's Daughter", 7.0),
 ('Slammerkin', 7.0),
 ('Stolen Lives: Twenty Years in a Desert Jail', 7.0),
 ('Cry to Heaven', 6.0),
 ('Merrick (Vampire Chronicles)', 6.0),
 ("Full House (Janet Evanovich's Full Series)", 7.0),
 ('Perfume: The Story of a Murderer (Vintage International)', 7.0),
 ('The Secret Garden (Book and Charm)', 5.0),
 ('Sabriel (The Abhorsen Trilogy)', 7.0),
 ('Coraline', 8.0),
 ('Knocked Out by My Nunga-Nungas : Further, Further Confessions of Georgia Nicolson (Confessions of Georgia Nicolson)',
  5.0),
 ('Love Is Hell: Special New Mini-Jumbo Edition With Extra Bonus Cartoons',
  5.0),
 ('The Arctic Incident (Artemis Fowl, Book 2)', 5.0),
 ('L Is for Lawless', 7.0),
 ("The Time Traveler's Wife (Harvest Book)", 10.0),
 ('The Cider House Rules', 7.0),
 ('Hotel Pastis: A Novel of Provence', 5.0),
 ('Timeline', 7.0),
 ('The Angel of Darkness', 7.0),
 ("Jewel (Oprah's Book Club)", 7.0),
 ('Morality for Beautiful Girls (No.1 Ladies Detective Agency)', 7.0),
 ('A Wrinkle in Time', 10.0),
 ('Charlie and the Great Glass Elevator: The Further Adventures of Charlie Bucket and Willie Wonka, Chocolate-Maker Extraordinary',
  5.0),
 ('Fried Green Tomatoes at the Whistle Stop Cafe', 7.0),
 ('The English Patient', 7.0),
 ('A Pirate Looks at Fifty', 6.0),
 ('Betsy-Tacy (Betsy-Tacy)', 5.0),
 ('WERE HISTORY : THE 20TH CENTURY SURVIVORS FINAL EXAM', 5.0),
 ('The LAST VAMPIRE (LAST VAMPIRE 1) : THE LAST VAMPIRE', 6.0),
 ('The World at Night : A Novel', 5.0),
 ('Cash: The Autobiography', 6.0),
 ('The Deep Blue Good-By', 6.0),
 ('Legacies: A Chinese Mosaic', 5.0),
 ('Fearless Jones', 5.0),
 ('Lasher', 6.0),
 ('Tar Baby', 5.0),
 ('The Forgotten: A Peter Decker/Rina Lazarus Novel', 6.0),
 ('Dragon Tears', 6.0),
 ('The Hope: A Novel', 5.0),
 ('Night Passage (Jesse Stone Novels (Paperback))', 6.0),
 ('Harry Potter and the Goblet of Fire (Book 4)', 8.0),
 ('A Common Life : The Wedding Story (The Mitford Years)', 6.0),
 ("All Tomorrow's Parties", 6.0),
 ('Biblioholism: The Literary Addiction', 5.0),
 ('Shane', 5.0),
 ("Ghost Soldiers: The Forgotten Epic Story of World War II's Most Dramatic Mission",
  6.0),
 ('Shepherds Abiding', 6.0),
 ('Koko', 5.0),
 ('Lies Across America : What Our Historic Sites Get Wrong', 5.0),
 ('Cat and Mouse', 7.0),
 ('The Grilling Season', 6.0),
 ("The Cheshire Cat's Eye", 5.0),
 ('Geek Love', 7.0),
 ('Hard Time (V.I. Warshawski Novels (Paperback))', 6.0),
 ('Even Cowgirls Get the Blues', 6.0),
 ('On Writing', 7.0),
 ('The Cross-Country Quilters', 6.0),
 ('The Mosquito Coast', 6.0),
 ('The Horse Whisperer', 7.0),
 ('River, Cross My Heart', 6.0),
 ('A Simple Plan', 8.0),
 ('Without Remorse', 6.0),
 ('It Was on Fire When I Lay Down on It', 7.0),
 ('Good Harbor: A Novel', 6.0),
 ('The Alibi', 6.0),
 ('The Man Who Listens to Horses', 6.0),
 ('What Dreams May Come : A Novel', 7.0),
 ('FORREST GUMP (Movie Tie in)', 7.0),
 ('Seven Up (A Stephanie Plum Novel)', 7.0),
 ('The Te of Piglet', 9.0),
 ('Tishomingo Blues', 6.0),
 ('The Dream of Scipio', 6.0),
 ('Tough Cookie', 6.0),
 ("The Devil's Arithmetic", 6.0),
 ('The Bone Collector (Lincoln Rhyme Novels (Paperback))', 7.0),
 ('Speaker for the Dead (Ender Wiggins Saga (Paperback))', 7.0),
 ('The Woman Warrior : Memoirs of a Girlhood Among Ghosts', 6.0),
 ('The Worst Day of My Life, So Far', 6.0),
 ('Too Many Crooks Spoil the Broth: A Pennsylvania-Dutch Mystery With Recipes (Pennsylvania Dutch Mysteries with Recipes (Paperback))',
  5.0),
 ('Couplehood', 7.0),
 ('Darkness, Take My Hand (Patrick Kenzie/Angela Gennaro Novels)', 6.0),
 ('A Painted House', 7.0),
 ("Ender's Game", 6.0),
 ('The Satanic Verses', 5.0),
 ('Immortality', 6.0),
 ('The Annotated Lolita', 5.0),
 ('One True Thing', 7.0),
 ('The Long Dark Tea-Time of the Soul', 10.0),
 ('Cause Celeb', 6.0),
 ('Johnny Got His Gun', 10.0),
 ('Stuart Little', 10.0),
 ('A Wind in the Door', 10.0),
 ('The Main Corpse (Culinary Mysteries (Paperback))', 7.0),
 ('The Hundred Secret Senses', 7.0),
 ("The Carbohydrate Addict's Diet: The Lifelong Solution to Yo-Yo Dieting",
  5.0),
 ("Bridget Jones's Diary", 7.0),
 ('The Killing Dance (Anita Blake Vampire Hunter (Paperback))', 6.0),
 ('The Prize Winner of Defiance, Ohio : How My Mother Raised 10 Kids on 25 Words or Less',
  6.0),
 ('Duplicate Keys', 6.0),
 ('Little House in the Big Woods', 7.0),
 ('Great Brain (Yearling)', 10.0),
 ('Blue Moon', 6.0),
 ('Inkheart', 6.0),
 ('Grass Roof, Tin Roof', 5.0),
 ('This Is My Family', 5.0),
 ('The Secret Life of Bees', 8.0),
 ('The Beauty Myth: How Images of Beauty Are Used Against Women', 6.0),
 ('The Master Butchers Singing Club : A Novel (Erdrich, Louise)', 6.0),
 ('Lucky Man: A Memoir', 7.0),
 ('Fatherhood', 6.0),
 ('Big Fish: A Novel of Mythic Proportions', 6.0),
 ('On a Pale Horse (Incarnations of Immortality, Bk. 1)', 7.0),
 ('Almost Adam', 6.0),
 ('Dead Man Walking: An Eyewitness Account of the Death Penalty in the United States',
  6.0),
 ('How to Be Good', 6.0),
 ('Numbered Account', 6.0),
 ('The Sheltering Sky (Vintage International)', 6.0),
 ("Dirk Gently's Holistic Detective Agency", 10.0),
 ("All I Know About Animal Behavior I Learned in Loehmann's Dressing Room",
  9.0),
 ('Hanging Up', 5.0),
 ('Lirael: Daughter of the Clayr', 6.0),
 ('Real Boys: Rescuing Our Sons from the Myths of Boyhood', 6.0),
 ('Every Living Thing', 10.0),
 ('\\Surely You\'re Joking, Mr. Feynman!\\": Adventures of a Curious Character"',
  6.0),
 ("The General's Daughter", 7.0),
 ('Wilderness Tips', 5.0),
 ('Juniper', 6.0),
 ('Artemis Fowl (Artemis Fowl, Book 1)', 8.0),
 ("Mammoth Hunters (Earth's Children)", 6.0),
 ('The Man in the Iron Mask (Signet Regency Romance)', 5.0),
 ('A Light in the Attic', 10.0),
 ('Catkin', 10.0),
 ('Star Wars Episode I: The Phantom Menace', 6.0),
 ("Dicey's Song", 10.0),
 ('The Hostile Hospital (A Series of Unfortunate Events, Book 8)', 6.0),
 ("Disney's 101 Dalmatians: The Movie Storybook", 5.0),
 ('A Wrinkle In Time', 10.0),
 ('Kristin Lavransdatter: The Bridal Wreath (Kristin Lavransdatter (Vintage))',
  8.0),
 ('Tourist Season', 9.0),
 ('Valley Of The Far Side', 6.0),
 ('Ella Minnow Pea: A Novel in Letters', 7.0),
 ('Strapless (Red Dress Ink (Paperback))', 6.0),
 ('More Random Acts of Kindness', 6.0),
 ('Simply Divine', 6.0),
 ("Beauty's Release", 6.0),
 ('Slave to Fashion : A Novel', 5.0),
 ('To the Lighthouse', 6.0),
 ('Joke', 5.0),
 ('Mutant Message Down Under', 8.0),
 ('Women Who Run with the Wolves', 6.0),
 ("Breakfast at Madeline's : A Jacob Burns Mystery ((Jacob Burns Mystery Series)",
  5.0),
 ('Tender at the Bone: Growing Up at the Table', 7.0),
 ('The Tesseract', 5.0),
 ('How Long Has This Been Going On (Stonewall Inn Editions)', 5.0),
 ("The Year's Best Fantasy and Horror: Ninth Annual Collection (Paper)", 5.0),
 ('To Dance With the White Dog', 6.0),
 ('The Kiss', 6.0),
 ('I Want to Grow Hair, I Want to Grow Up, I Want to Go to Boise (Children Surviving Cancer)',
  6.0),
 ('The Gold-Bug and Other Tales (Dover Thrift Editions)', 6.0),
 ('The Necklace and Other Short Stories (Dover Thrift Editions)', 5.0),
 ('The Cardinal of the Kremlin', 6.0),
 ('The True Confessions of Charlotte Doyle (rack)', 6.0),
 ("Dunn's Conundrum", 5.0),
 ('Playing Away', 5.0),
 ('Gut Symmetries', 5.0),
 ("Mama Get The Hammer! There's A Fly On Papa's Head!", 5.0),
 ('Undead and Unwed (Berkley Sensation)', 8.0),
 ('Wahiawa: From dream to community', 5.0),
 ('The PASSION OF AN ANGEL : THE PASSION OF AN ANGEL', 5.0),
 ('MRS FRISBY AND THE RATS OF NIMH', 5.0),
 ('The Burning Point', 5.0),
 ('Into the Thinking Kingdoms (Journeys of the Catechist, Book 2)', 5.0),
 ('A Triumph of Souls (Journeys of the Catechist, Book 3)', 5.0),
 ('Angle of Impact', 5.0),
 ('Vengeance Is Hers', 5.0),
 ('Angry Lead Skies (Garrett P.I.)', 5.0),
 ('The Mammoth Stone', 5.0),
 ('Men in Black: A Novel', 5.0),
 ('Ruby Slippers, Golden Tears', 6.0),
 ('Pawing Through the Past (Mrs. Murphy Mysteries (Paperback))', 6.0),
 ('Magnificat (Galactic Milieu Trilogy, No 3)', 5.0),
 ('Cosbyology: Essays and Observations from the Doctor of Comedy', 5.0),
 ('Finding Forrester: A Novel', 5.0),
 ('The Fall (Vintage International)', 5.0),
 ('Round Robin: An Elm Creek Quilts Novel (Elm Creek Quilters Novels)', 6.0),
 ('The First Four Years (Little House)', 6.0),
 ('The Littles Have a Wedding (Littles)', 5.0),
 ('Coyote Blue', 6.0),
 ('Unnatural Selections', 6.0),
 ('DINOSAUR ISLAND (Choose Your Own Adventure, No 138)', 5.0),
 ('Legs Benedict: : A Bed-And-breakfast Mystery (Bed-And-Breakfast Mysteries (Paperback))',
  5.0),
 ('The Chocolate War (Laurel Leaf Books)', 6.0),
 ('Next Stop, Paradise (Avon Light Contemporary Romances)', 5.0),
 ('Women on the Case', 5.0),
 ('Murder of a Snake in the Grass (Scumble River Mysteries)', 5.0),
 ('Murder of a Barbie and Ken (National Bestselling Series)', 6.0),
 ('Catfantastic II (Daw Book Collectors)', 6.0),
 ("Something's Cooking (Angie Amalfi Mysteries)", 5.0),
 ('Say No to Joe?', 6.0),
 ('Sam Walton: Made in America : My Story', 5.0),
 ('Murder at Monticello (Mrs. Murphy Mysteries (Paperback))', 5.0),
 ("Ranch of Dreams: The Heartwarming Story of America's Most Unusual Animal Sanctuary",
  5.0),
 ('We Are Still Married: Stories and Letters', 5.0),
 ('Me: by Jimmy (Big Boy) Valente', 5.0),
 ('Headlines III : Not the Movie, Still the Book', 5.0),
 ("The Concubine's Tattoo (A Sano Ichiro Mystery)", 6.0),
 ('Rough Justice', 6.0),
 ('Before Women Had Wings', 5.0),
 ('Kindred (Black Women Writers Series)', 9.0),
 ('The Dance of Trees', 6.0),
 ('Eddie Would Go : The Story of Eddie Aikau, Hawaiian Hero and Pioneer of Big Wave Surfing',
  9.0),
 ('The Lion, the Witch and the Wardrobe', 10.0),
 ('The Veil of Snows', 10.0),
 ('A City in Winter', 8.0),
 ('Swan Lake', 10.0),
 ('An Instance of the Fingerpost', 6.0),
 ('Cats Know Best (Pied Piper Paperbacks)', 5.0),
 ('How to Be a Financially Secure Woman', 5.0),
 ('The Npr Interviews 1994', 10.0),
 ('The Neverending Story', 10.0),
 ('Frugal Gourmet', 9.0),
 ('Depeche Mode: Some Great Reward', 10.0),
 ('Farewell to My Concubine: A Novel', 5.0),
 ('I Ching -- The classic Chinese Oracle of Change. The first complete translation with concordance',
  10.0),
 ('Hope for the Flowers', 10.0),
 ('Twentynine Palms : A True Story of Murder, Marines, and the Mojave', 5.0),
 ('Read to Your Bunny', 10.0),
 ('HOW GREEN WAS MY VALLEY', 10.0),
 ('The Dollmaker', 10.0),
 ('The Collected Stories of Eudora Welty', 10.0),
 ("Fall on Your Knees (Oprah's Book Club)", 6.0),
 ("Are You There God?  It's Me, Margaret", 7.0),
 ('Young Wives', 6.0),
 ('Everlasting Love', 5.0),
 ('Cabin', 6.0),
 ('The Observatory : A Novel', 5.0),
 ('Gods and Generals', 6.0),
 ('Chili Dawgs Always Bark at Night', 5.0),
 ('Why She Left Us', 5.0),
 ('Into the Tangle of Friendship : A Memoir of the Things That Matter', 5.0),
 ('Wizard in the Tree', 5.0),
 ('Redemption Song', 5.0),
 ('Mikwright Family Style', 9.0),
 ('A Christmas Story : The Book That Inspired the Hilarious Classic Film',
  5.0),
 ('Pour Your Heart into It: How Starbucks Built a Company One Cup at a Time',
  5.0),
 ('Blanche Passes Go', 5.0),
 ('Everything In Its Place: My Trials and Triumphs with Obsessive Compulsive Disorder',

### Find predicted ratings for the user for all the books, which were not rated by him/her

In [56]:
# reference: https://surprise.readthedocs.io/en/stable/algobase.html?highlight=predict
# uid – (Raw) id of the user. 
# iid – (Raw) id of the item.
# verbose (bool) – Whether to print details of the prediction. Default is False.

predictions=[svd_default_model.predict(uid=user_id, iid=i) for i in titles_input_to_recommend]
predictions[:5]

[Prediction(uid=6251, iid='Clara Callan', r_ui=None, est=6.622579770799428, details={'was_impossible': False}),
 Prediction(uid=6251, iid='Decision in Normandy', r_ui=None, est=6.169392752492404, details={'was_impossible': False}),
 Prediction(uid=6251, iid='Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It', r_ui=None, est=5.550156902757992, details={'was_impossible': False}),
 Prediction(uid=6251, iid="What If?: The World's Foremost Military Historians Imagine What Might Have Been", r_ui=None, est=5.851956054006721, details={'was_impossible': False}),
 Prediction(uid=6251, iid='PLEADING GUILTY', r_ui=None, est=6.169392752492404, details={'was_impossible': False})]

In [57]:
# check of there are any predictions with 'was_impossible': True
predictions_impossible=[i for i in predictions if i.details['was_impossible']==True]
predictions_impossible

[]

In [58]:
# get ratings estimate for books by the user
ratings=[i.est for i in predictions]
ratings[:5]

[6.622579770799428,
 6.169392752492404,
 5.550156902757992,
 5.851956054006721,
 6.169392752492404]

In [59]:
# convert predicted estimates by the user for not read books into df
pred_dict={
    'Book_Title':titles_input_to_recommend,
    'Estimated_Rate':ratings}
predictions_book=pd.DataFrame(pred_dict).sort_values('Estimated_Rate',ascending = False)
predictions_book

                                              Book_Title  Estimated_Rate
27                                 To Kill a Mockingbird        9.338332
878                                   Dragonfly in Amber        9.014975
2643   The Hobbit : The Enchanting Prelude to The Lor...        8.994067
603       The Two Towers (The Lord of the Rings, Part 2)        8.936750
3009                    Charlotte's Web (Trophy Newbery)        8.886899
...                                                  ...             ...
16685     The Celestine Prophecy : AN EXPERIENTIAL GUIDE        4.507433
33304                                 Black Coffee Blues        4.488741
4894                                The Tailor of Panama        4.473716
39219                         The Burning Times: A Novel        4.452318
17055  Miss Zukas and the Library Murders (Miss Zukas...        4.404791

[133076 rows x 2 columns]

In [60]:
print(f'for a user {user_id}, who read the following book(s), with ratings shown:') 
display(rated_book_title_rate)
print('The recommendation is following:')
display(predictions_book.head(recommendations_count))

for a user 6251, who read the following book(s), with ratings shown:

[('Wild Animus', 4.0),
 ('Timeline', 8.0),
 ('Isle of Dogs', 5.0),
 ('A Soldier of the Great War', 7.0),
 ('The Joy Luck Club', 8.0),
 ('The Tao of Pooh', 10.0),
 ('Seabiscuit', 7.0),
 ("Life's Little Instruction Book (Life's Little Instruction Books (Paperback))",
  7.0),
 ('Starship Troopers', 7.0),
 ("Corelli's Mandolin : A Novel", 7.0),
 ('The Five People You Meet in Heaven', 8.0),
 ('The Sum of All Fears', 7.0),
 ('Little Altars Everywhere: A Novel', 7.0),
 ('Body of Evidence (Kay Scarpetta Mysteries (Paperback))', 7.0),
 ('The Rescue', 7.0),
 ("The Kalahari Typing School for Men (No. 1 Ladies' Detective Agency)", 7.0),
 ('Wicked: The Life and Times of the Wicked Witch of the West', 7.0),
 ('Lies and the Lying Liars Who Tell Them: A Fair and Balanced Look at the Right',
  8.0),
 ("On the Bright Side, I'm Now the Girlfriend of a Sex God: Further Confessions of Georgia Nicolson",
  6.0),
 ('Eva Luna', 7.0),
 ('A Man in Full', 6.0),
 ("Vinegar Hill (Oprah's Book Club (Paperback))", 6.0),
 ('Bel Canto', 7.0),
 ('Lakota Woman', 6.0),
 ('The Perfect Storm : A True Story of Men Against the Sea', 7.0),
 ('Hannibal', 6.0),
 ('Cavedweller', 6.0),
 ('The Firm', 8.0),
 ('The Scarlet Letter', 7.0),
 ("She's Come Undone (Oprah's Book Club)", 7.0),
 ('Nickel and Dimed: On (Not) Getting By in America', 8.0),
 ('The Diary of Ellen Rimbauer: My Life at Rose Red', 6.0),
 ('Be Cool', 5.0),
 ('The Bean Trees', 8.0),
 ('Daughter of Fortune', 7.0),
 ('The Red Tent (Bestselling Backlist)', 8.0),
 ('The Nanny Diaries: A Novel', 7.0),
 ('Everything Is Illuminated: A Novel', 6.0),
 ('Prince Caspian', 6.0),
 ("Angela's Ashes: A Memoir", 8.0),
 ('Fast Food Nation: The Dark Side of the All-American Meal', 8.0),
 ('One for the Money (Stephanie Plum Novels (Paperback))', 7.0),
 ("Where the Heart Is (Oprah's Book Club (Paperback))", 8.0),
 ("The Girls' Guide to Hunting and Fishing", 7.0),
 ('Blackbird: A Childhood Lost and Found', 7.0),
 ('Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
  7.0),
 ('All the Pretty Horses (Border Trilogy, Vol 1)', 6.0),
 ('The Bad Beginning (A Series of Unfortunate Events, Book 1)', 7.0),
 ('About a Boy (Movie Tie-In)', 7.0),
 ("Smilla's Sense of Snow", 6.0),
 ("The Magician's Nephew (Narnia)", 8.0),
 ('The Phantom Tollbooth', 10.0),
 ('SHIPPING NEWS', 7.0),
 ('Reap the Wind', 7.0),
 ('Frankenstein Or, the Modern Prometheus', 6.0),
 ('American Gods', 7.0),
 ('Tales of the City (Tales of the City Series, V. 1)', 7.0),
 ('Red Dragon', 7.0),
 ('Jurassic Park', 8.0),
 ('The God of Small Things', 6.0),
 ('Mother of Pearl', 6.0),
 ("Lamb : The Gospel According to Biff, Christ's Childhood Pal", 10.0),
 ('Nickel and Dimed: On (Not) Getting By in America', 7.0),
 ('Good Omens', 10.0),
 ('The Poisonwood Bible: A Novel', 8.0),
 ("Operating Instructions: A Journal of My Son's First Year", 7.0),
 ('Jewel', 7.0),
 ('The Prophet', 10.0),
 ("The No. 1 Ladies' Detective Agency (Today Show Book Club #8)", 8.0),
 ('Shopgirl', 8.0),
 ('The Devil in the White City : Murder, Magic, and Madness at the Fair That Changed America (Illinois)',
  7.0),
 ("The Kitchen God's Wife", 7.0),
 ("Songs in Ordinary Time (Oprah's Book Club (Paperback))", 6.0),
 ('Good in Bed', 8.0),
 ('Out of Sight', 6.0),
 ('How to Make an American Quilt', 6.0),
 ('The Years of Rice and Salt', 6.0),
 ('A Heartbreaking Work of Staggering Genius', 4.0),
 ('The Eyre Affair (Alex Awards (Awards))', 7.0),
 ('A Year in Provence', 7.0),
 ('The Indian in the Cupboard', 10.0),
 ('What to Expect the First Year', 7.0),
 ('The Partner', 7.0),
 ('The Alienist', 7.0),
 ('The Smoke Jumper', 7.0),
 ("The Ultimate Hitchhiker's Guide", 10.0),
 ('To Cut a Long Story Short', 6.0),
 ('Fg on Our Immigrant Ance', 10.0),
 ('Fg Cooks American', 9.0),
 ('Into Thin Air : A Personal Account of the Mt. Everest Disaster', 8.0),
 ('Snow Falling on Cedars', 8.0),
 ('Leaving Home', 9.0),
 ('The Lost World', 7.0),
 ("The Shelters of Stone (Earth's Children Series, No 5)", 3.0),
 ("A Room of One's Own", 6.0),
 ('Lucky You', 6.0),
 ("CAT'S EYE", 6.0),
 ("The Handmaid's Tale", 8.0),
 ('White Oleander : A Novel', 8.0),
 ('Out to Canaan (The Mitford Years)', 6.0),
 ('These High, Green Hills (The Mitford Years)', 8.0),
 ('A Light in the Window (The Mitford Years)', 7.0),
 ("Reviving Ophelia: Saving the Selves of Adolescent Girls (Ballantine Reader's Circle)",
  8.0),
 ("Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))", 9.0),
 ('Skinny Legs and All', 7.0),
 ("Ender's Game (Ender Wiggins Saga (Paperback))", 8.0),
 ("Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
  7.0),
 ('Mystic River', 7.0),
 ('Sick Puppy', 7.0),
 ('One', 6.0),
 ('Babyhood', 7.0),
 ('Interview with the Vampire', 8.0),
 ('The Queen of the Damned (Vampire Chronicles (Paperback))', 7.0),
 ('A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
  7.0),
 ('Reading Lolita in Tehran: A Memoir in Books', 7.0),
 ('How to Talk So Kids Will Listen and Listen So Kids Will Talk', 6.0),
 ('The Visitor (Animorphs, No 2)', 6.0),
 ('Standing in the Rainbow', 7.0),
 ('Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
  10.0),
 ("Dude, Where's My Country?", 10.0),
 ('Homecoming', 6.0),
 ('The Tale of the Body Thief (Vampire Chronicles (Paperback))', 7.0),
 ('Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))', 7.0),
 ('The Hours: A Novel', 7.0),
 ('Carrie Pilby (Red Dress Ink (Paperback))', 6.0),
 ('Behind the Scenes at the Museum : A Novel', 6.0),
 ('Follow the River', 6.0),
 ('The Runaway Jury', 7.0),
 ('The Experiment (Animorphs, No 28)', 5.0),
 ('The Mambo Kings Play Songs of Love', 6.0),
 ('Harry Potter and the Chamber of Secrets (Book 2)', 8.0),
 ('The Curious Incident of the Dog in the Night-Time (Vintage Contemporaries)',
  10.0),
 ('Sula', 6.0),
 ('The Kite Runner (Alex Awards (Awards))', 6.0),
 ('A BEAUTIFUL MIND: A Biography of John Forbes Nash, Jr., Winner of the Nobel Prize in Economics, 1994',
  6.0),
 ('Island of the Sequined L', 8.0),
 ('The King Must Die', 6.0),
 ('The Autobiography of Miss Jane Pittman', 5.0),
 ('Basket Case', 7.0),
 ('4 Blondes', 5.0),
 ('Night', 8.0),
 ("Winter's Tale", 10.0),
 ('The Cat in the Hat', 10.0),
 ('Harry Potter and the Prisoner of Azkaban (Book 3)', 10.0),
 ('Battlefield Earth: A Saga of the Year 3000', 6.0),
 ('Primary Colors: A Novel of Politics', 6.0),
 ('American Fuji', 6.0),
 ('Yukon Ho!', 10.0),
 ('Eat Mangoes Naked : Finding Pleasure Everywhere (and dancing with the Pits)',
  8.0),
 ('Transformation Soup : Healing for the Splendidly Imperfect', 6.0),
 ('K Is for Killer (Kinsey Millhone Mysteries (Paperback))', 7.0),
 ('The Bourne Identity', 7.0),
 ('Cat in the Hat (I Can Read It All by Myself Beginner Books)', 6.0),
 ("The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))",
  7.0),
 ('Confessions of a Failed Southern Lady', 6.0),
 ("Charlotte's Web", 7.0),
 ('Mrs Dalloway', 6.0),
 ("White Oleander : A Novel (Oprah's Book Club)", 7.0),
 ('A Widow for One Year : A Novel', 6.0),
 ('Running with Scissors', 6.0),
 ('Confessions of an Ugly Stepsister : A Novel', 7.0),
 ('Zen and the Art of Motorcycle Maintenance: An Inquiry into Values', 7.0),
 ('Stardust', 7.0),
 ('Dying for Chocolate (Culinary Mysteries (Paperback))', 7.0),
 ('Lucky You', 8.0),
 ('Pagan Babies', 6.0),
 ('Prime Cut', 6.0),
 ("The Girls' Guide to Hunting and Fishing", 6.0),
 ('The Pleasure of My Company: A Novel', 10.0),
 ('House of Sand and Fog', 6.0),
 ('The Hot Zone', 7.0),
 ('Nerd in Shining Armor', 6.0),
 ('The Reptile Room (A Series of Unfortunate Events, Book 2)', 7.0),
 ('The Corrections', 6.0),
 ('A Case of Need', 6.0),
 ('The Devil Wears Prada : A Novel', 6.0),
 ('All the Trouble in the World: The Lighter Side of Overpopulation, Famine, Ecological Disaster, Ethnic Hatred, Plague, and Poverty',
  5.0),
 ('A Book Without Covers', 6.0),
 ('The Tenth Justice', 6.0),
 ('East of Eden', 6.0),
 ('All I Really Need to Know', 7.0),
 ('Plague Dogs', 6.0),
 ('Harry Potter and the Goblet of Fire (Book 4)', 10.0),
 ('Redwall (Redwall, Book 1)', 7.0),
 ('Harry Potter and the Order of the Phoenix (Book 5)', 9.0),
 ('Insomnia', 7.0),
 ('Tears of the Giraffe (No.1 Ladies Detective Agency)', 8.0),
 ('Holes (Yearling Newbery)', 8.0),
 ('Time Flies', 6.0),
 ("It's Not About the Bike: My Journey Back to Life", 7.0),
 ('The Blind Assassin', 7.0),
 ('The Butter Did It : A Gastronomic Tale of Love and Murder (Chas Wheatley Mysteries)',
  5.0),
 ('Plainsong', 6.0),
 ('Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
  9.0),
 ('A Short Guide to a Happy Life', 7.0),
 ('Two for the Dough', 8.0),
 ('Bless Me, Ultima', 6.0),
 ('The Emperor of Ocean Park (Today Show Book Club #1)', 7.0),
 ("The Bonesetter's Daughter", 7.0),
 ('Slammerkin', 7.0),
 ('Stolen Lives: Twenty Years in a Desert Jail', 7.0),
 ('Cry to Heaven', 6.0),
 ('Merrick (Vampire Chronicles)', 6.0),
 ("Full House (Janet Evanovich's Full Series)", 7.0),
 ('Perfume: The Story of a Murderer (Vintage International)', 7.0),
 ('The Secret Garden (Book and Charm)', 5.0),
 ('Sabriel (The Abhorsen Trilogy)', 7.0),
 ('Coraline', 8.0),
 ('Knocked Out by My Nunga-Nungas : Further, Further Confessions of Georgia Nicolson (Confessions of Georgia Nicolson)',
  5.0),
 ('Love Is Hell: Special New Mini-Jumbo Edition With Extra Bonus Cartoons',
  5.0),
 ('The Arctic Incident (Artemis Fowl, Book 2)', 5.0),
 ('L Is for Lawless', 7.0),
 ("The Time Traveler's Wife (Harvest Book)", 10.0),
 ('The Cider House Rules', 7.0),
 ('Hotel Pastis: A Novel of Provence', 5.0),
 ('Timeline', 7.0),
 ('The Angel of Darkness', 7.0),
 ("Jewel (Oprah's Book Club)", 7.0),
 ('Morality for Beautiful Girls (No.1 Ladies Detective Agency)', 7.0),
 ('A Wrinkle in Time', 10.0),
 ('Charlie and the Great Glass Elevator: The Further Adventures of Charlie Bucket and Willie Wonka, Chocolate-Maker Extraordinary',
  5.0),
 ('Fried Green Tomatoes at the Whistle Stop Cafe', 7.0),
 ('The English Patient', 7.0),
 ('A Pirate Looks at Fifty', 6.0),
 ('Betsy-Tacy (Betsy-Tacy)', 5.0),
 ('WERE HISTORY : THE 20TH CENTURY SURVIVORS FINAL EXAM', 5.0),
 ('The LAST VAMPIRE (LAST VAMPIRE 1) : THE LAST VAMPIRE', 6.0),
 ('The World at Night : A Novel', 5.0),
 ('Cash: The Autobiography', 6.0),
 ('The Deep Blue Good-By', 6.0),
 ('Legacies: A Chinese Mosaic', 5.0),
 ('Fearless Jones', 5.0),
 ('Lasher', 6.0),
 ('Tar Baby', 5.0),
 ('The Forgotten: A Peter Decker/Rina Lazarus Novel', 6.0),
 ('Dragon Tears', 6.0),
 ('The Hope: A Novel', 5.0),
 ('Night Passage (Jesse Stone Novels (Paperback))', 6.0),
 ('Harry Potter and the Goblet of Fire (Book 4)', 8.0),
 ('A Common Life : The Wedding Story (The Mitford Years)', 6.0),
 ("All Tomorrow's Parties", 6.0),
 ('Biblioholism: The Literary Addiction', 5.0),
 ('Shane', 5.0),
 ("Ghost Soldiers: The Forgotten Epic Story of World War II's Most Dramatic Mission",
  6.0),
 ('Shepherds Abiding', 6.0),
 ('Koko', 5.0),
 ('Lies Across America : What Our Historic Sites Get Wrong', 5.0),
 ('Cat and Mouse', 7.0),
 ('The Grilling Season', 6.0),
 ("The Cheshire Cat's Eye", 5.0),
 ('Geek Love', 7.0),
 ('Hard Time (V.I. Warshawski Novels (Paperback))', 6.0),
 ('Even Cowgirls Get the Blues', 6.0),
 ('On Writing', 7.0),
 ('The Cross-Country Quilters', 6.0),
 ('The Mosquito Coast', 6.0),
 ('The Horse Whisperer', 7.0),
 ('River, Cross My Heart', 6.0),
 ('A Simple Plan', 8.0),
 ('Without Remorse', 6.0),
 ('It Was on Fire When I Lay Down on It', 7.0),
 ('Good Harbor: A Novel', 6.0),
 ('The Alibi', 6.0),
 ('The Man Who Listens to Horses', 6.0),
 ('What Dreams May Come : A Novel', 7.0),
 ('FORREST GUMP (Movie Tie in)', 7.0),
 ('Seven Up (A Stephanie Plum Novel)', 7.0),
 ('The Te of Piglet', 9.0),
 ('Tishomingo Blues', 6.0),
 ('The Dream of Scipio', 6.0),
 ('Tough Cookie', 6.0),
 ("The Devil's Arithmetic", 6.0),
 ('The Bone Collector (Lincoln Rhyme Novels (Paperback))', 7.0),
 ('Speaker for the Dead (Ender Wiggins Saga (Paperback))', 7.0),
 ('The Woman Warrior : Memoirs of a Girlhood Among Ghosts', 6.0),
 ('The Worst Day of My Life, So Far', 6.0),
 ('Too Many Crooks Spoil the Broth: A Pennsylvania-Dutch Mystery With Recipes (Pennsylvania Dutch Mysteries with Recipes (Paperback))',
  5.0),
 ('Couplehood', 7.0),
 ('Darkness, Take My Hand (Patrick Kenzie/Angela Gennaro Novels)', 6.0),
 ('A Painted House', 7.0),
 ("Ender's Game", 6.0),
 ('The Satanic Verses', 5.0),
 ('Immortality', 6.0),
 ('The Annotated Lolita', 5.0),
 ('One True Thing', 7.0),
 ('The Long Dark Tea-Time of the Soul', 10.0),
 ('Cause Celeb', 6.0),
 ('Johnny Got His Gun', 10.0),
 ('Stuart Little', 10.0),
 ('A Wind in the Door', 10.0),
 ('The Main Corpse (Culinary Mysteries (Paperback))', 7.0),
 ('The Hundred Secret Senses', 7.0),
 ("The Carbohydrate Addict's Diet: The Lifelong Solution to Yo-Yo Dieting",
  5.0),
 ("Bridget Jones's Diary", 7.0),
 ('The Killing Dance (Anita Blake Vampire Hunter (Paperback))', 6.0),
 ('The Prize Winner of Defiance, Ohio : How My Mother Raised 10 Kids on 25 Words or Less',
  6.0),
 ('Duplicate Keys', 6.0),
 ('Little House in the Big Woods', 7.0),
 ('Great Brain (Yearling)', 10.0),
 ('Blue Moon', 6.0),
 ('Inkheart', 6.0),
 ('Grass Roof, Tin Roof', 5.0),
 ('This Is My Family', 5.0),
 ('The Secret Life of Bees', 8.0),
 ('The Beauty Myth: How Images of Beauty Are Used Against Women', 6.0),
 ('The Master Butchers Singing Club : A Novel (Erdrich, Louise)', 6.0),
 ('Lucky Man: A Memoir', 7.0),
 ('Fatherhood', 6.0),
 ('Big Fish: A Novel of Mythic Proportions', 6.0),
 ('On a Pale Horse (Incarnations of Immortality, Bk. 1)', 7.0),
 ('Almost Adam', 6.0),
 ('Dead Man Walking: An Eyewitness Account of the Death Penalty in the United States',
  6.0),
 ('How to Be Good', 6.0),
 ('Numbered Account', 6.0),
 ('The Sheltering Sky (Vintage International)', 6.0),
 ("Dirk Gently's Holistic Detective Agency", 10.0),
 ("All I Know About Animal Behavior I Learned in Loehmann's Dressing Room",
  9.0),
 ('Hanging Up', 5.0),
 ('Lirael: Daughter of the Clayr', 6.0),
 ('Real Boys: Rescuing Our Sons from the Myths of Boyhood', 6.0),
 ('Every Living Thing', 10.0),
 ('\\Surely You\'re Joking, Mr. Feynman!\\": Adventures of a Curious Character"',
  6.0),
 ("The General's Daughter", 7.0),
 ('Wilderness Tips', 5.0),
 ('Juniper', 6.0),
 ('Artemis Fowl (Artemis Fowl, Book 1)', 8.0),
 ("Mammoth Hunters (Earth's Children)", 6.0),
 ('The Man in the Iron Mask (Signet Regency Romance)', 5.0),
 ('A Light in the Attic', 10.0),
 ('Catkin', 10.0),
 ('Star Wars Episode I: The Phantom Menace', 6.0),
 ("Dicey's Song", 10.0),
 ('The Hostile Hospital (A Series of Unfortunate Events, Book 8)', 6.0),
 ("Disney's 101 Dalmatians: The Movie Storybook", 5.0),
 ('A Wrinkle In Time', 10.0),
 ('Kristin Lavransdatter: The Bridal Wreath (Kristin Lavransdatter (Vintage))',
  8.0),
 ('Tourist Season', 9.0),
 ('Valley Of The Far Side', 6.0),
 ('Ella Minnow Pea: A Novel in Letters', 7.0),
 ('Strapless (Red Dress Ink (Paperback))', 6.0),
 ('More Random Acts of Kindness', 6.0),
 ('Simply Divine', 6.0),
 ("Beauty's Release", 6.0),
 ('Slave to Fashion : A Novel', 5.0),
 ('To the Lighthouse', 6.0),
 ('Joke', 5.0),
 ('Mutant Message Down Under', 8.0),
 ('Women Who Run with the Wolves', 6.0),
 ("Breakfast at Madeline's : A Jacob Burns Mystery ((Jacob Burns Mystery Series)",
  5.0),
 ('Tender at the Bone: Growing Up at the Table', 7.0),
 ('The Tesseract', 5.0),
 ('How Long Has This Been Going On (Stonewall Inn Editions)', 5.0),
 ("The Year's Best Fantasy and Horror: Ninth Annual Collection (Paper)", 5.0),
 ('To Dance With the White Dog', 6.0),
 ('The Kiss', 6.0),
 ('I Want to Grow Hair, I Want to Grow Up, I Want to Go to Boise (Children Surviving Cancer)',
  6.0),
 ('The Gold-Bug and Other Tales (Dover Thrift Editions)', 6.0),
 ('The Necklace and Other Short Stories (Dover Thrift Editions)', 5.0),
 ('The Cardinal of the Kremlin', 6.0),
 ('The True Confessions of Charlotte Doyle (rack)', 6.0),
 ("Dunn's Conundrum", 5.0),
 ('Playing Away', 5.0),
 ('Gut Symmetries', 5.0),
 ("Mama Get The Hammer! There's A Fly On Papa's Head!", 5.0),
 ('Undead and Unwed (Berkley Sensation)', 8.0),
 ('Wahiawa: From dream to community', 5.0),
 ('The PASSION OF AN ANGEL : THE PASSION OF AN ANGEL', 5.0),
 ('MRS FRISBY AND THE RATS OF NIMH', 5.0),
 ('The Burning Point', 5.0),
 ('Into the Thinking Kingdoms (Journeys of the Catechist, Book 2)', 5.0),
 ('A Triumph of Souls (Journeys of the Catechist, Book 3)', 5.0),
 ('Angle of Impact', 5.0),
 ('Vengeance Is Hers', 5.0),
 ('Angry Lead Skies (Garrett P.I.)', 5.0),
 ('The Mammoth Stone', 5.0),
 ('Men in Black: A Novel', 5.0),
 ('Ruby Slippers, Golden Tears', 6.0),
 ('Pawing Through the Past (Mrs. Murphy Mysteries (Paperback))', 6.0),
 ('Magnificat (Galactic Milieu Trilogy, No 3)', 5.0),
 ('Cosbyology: Essays and Observations from the Doctor of Comedy', 5.0),
 ('Finding Forrester: A Novel', 5.0),
 ('The Fall (Vintage International)', 5.0),
 ('Round Robin: An Elm Creek Quilts Novel (Elm Creek Quilters Novels)', 6.0),
 ('The First Four Years (Little House)', 6.0),
 ('The Littles Have a Wedding (Littles)', 5.0),
 ('Coyote Blue', 6.0),
 ('Unnatural Selections', 6.0),
 ('DINOSAUR ISLAND (Choose Your Own Adventure, No 138)', 5.0),
 ('Legs Benedict: : A Bed-And-breakfast Mystery (Bed-And-Breakfast Mysteries (Paperback))',
  5.0),
 ('The Chocolate War (Laurel Leaf Books)', 6.0),
 ('Next Stop, Paradise (Avon Light Contemporary Romances)', 5.0),
 ('Women on the Case', 5.0),
 ('Murder of a Snake in the Grass (Scumble River Mysteries)', 5.0),
 ('Murder of a Barbie and Ken (National Bestselling Series)', 6.0),
 ('Catfantastic II (Daw Book Collectors)', 6.0),
 ("Something's Cooking (Angie Amalfi Mysteries)", 5.0),
 ('Say No to Joe?', 6.0),
 ('Sam Walton: Made in America : My Story', 5.0),
 ('Murder at Monticello (Mrs. Murphy Mysteries (Paperback))', 5.0),
 ("Ranch of Dreams: The Heartwarming Story of America's Most Unusual Animal Sanctuary",
  5.0),
 ('We Are Still Married: Stories and Letters', 5.0),
 ('Me: by Jimmy (Big Boy) Valente', 5.0),
 ('Headlines III : Not the Movie, Still the Book', 5.0),
 ("The Concubine's Tattoo (A Sano Ichiro Mystery)", 6.0),
 ('Rough Justice', 6.0),
 ('Before Women Had Wings', 5.0),
 ('Kindred (Black Women Writers Series)', 9.0),
 ('The Dance of Trees', 6.0),
 ('Eddie Would Go : The Story of Eddie Aikau, Hawaiian Hero and Pioneer of Big Wave Surfing',
  9.0),
 ('The Lion, the Witch and the Wardrobe', 10.0),
 ('The Veil of Snows', 10.0),
 ('A City in Winter', 8.0),
 ('Swan Lake', 10.0),
 ('An Instance of the Fingerpost', 6.0),
 ('Cats Know Best (Pied Piper Paperbacks)', 5.0),
 ('How to Be a Financially Secure Woman', 5.0),
 ('The Npr Interviews 1994', 10.0),
 ('The Neverending Story', 10.0),
 ('Frugal Gourmet', 9.0),
 ('Depeche Mode: Some Great Reward', 10.0),
 ('Farewell to My Concubine: A Novel', 5.0),
 ('I Ching -- The classic Chinese Oracle of Change. The first complete translation with concordance',
  10.0),
 ('Hope for the Flowers', 10.0),
 ('Twentynine Palms : A True Story of Murder, Marines, and the Mojave', 5.0),
 ('Read to Your Bunny', 10.0),
 ('HOW GREEN WAS MY VALLEY', 10.0),
 ('The Dollmaker', 10.0),
 ('The Collected Stories of Eudora Welty', 10.0),
 ("Fall on Your Knees (Oprah's Book Club)", 6.0),
 ("Are You There God?  It's Me, Margaret", 7.0),
 ('Young Wives', 6.0),
 ('Everlasting Love', 5.0),
 ('Cabin', 6.0),
 ('The Observatory : A Novel', 5.0),
 ('Gods and Generals', 6.0),
 ('Chili Dawgs Always Bark at Night', 5.0),
 ('Why She Left Us', 5.0),
 ('Into the Tangle of Friendship : A Memoir of the Things That Matter', 5.0),
 ('Wizard in the Tree', 5.0),
 ('Redemption Song', 5.0),
 ('Mikwright Family Style', 9.0),
 ('A Christmas Story : The Book That Inspired the Hilarious Classic Film',
  5.0),
 ('Pour Your Heart into It: How Starbucks Built a Company One Cup at a Time',
  5.0),
 ('Blanche Passes Go', 5.0),
 ('Everything In Its Place: My Trials and Triumphs with Obsessive Compulsive Disorder',

The recommendation is following:

                                             Book_Title  Estimated_Rate
27                                To Kill a Mockingbird        9.338332
878                                  Dragonfly in Amber        9.014975
2643  The Hobbit : The Enchanting Prelude to The Lor...        8.994067
603      The Two Towers (The Lord of the Rings, Part 2)        8.936750
3009                   Charlotte's Web (Trophy Newbery)        8.886899

In [67]:
# prediction_full_info=pd.merge(predictions_book, books_df, left_on='Book_Title',right_on='Book-Title', how='left')
# prediction_full_info=prediction_full_info[['Book_Title','Book-Author','Year-Of-Publication','Publisher', 'Estimated_Rate']]
# prediction_full_info.head(20)

,Book_Title,Book-Author,Year-Of-Publication,Publisher,Estimated_Rate
0,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,9.338332
1,To Kill a Mockingbird,Harper Lee,1985,Warner Books,9.338332
2,To Kill a Mockingbird,Harper Lee,2002,Perennial Classics,9.338332
3,To Kill a Mockingbird,Harper Lee,1960,Harpercollins,9.338332
4,To Kill a Mockingbird,Harper Lee,1995,HarperCollins Publishers,9.338332
5,To Kill a Mockingbird,Harper Lee,1982,Not Avail,9.338332
6,To Kill a Mockingbird,Harper Lee,1997,Audio Partners,9.338332
7,To Kill a Mockingbird,Harper Lee,1991,Buccaneer Books Inc,9.338332
8,Dragonfly in Amber,DIANA GABALDON,1993,Dell,9.014975
9,Dragonfly in Amber,DIANA GABALDON,1992,Delacorte Press,9.014975
10,Dragonfly in Amber,DIANA GABALDON,2001,Delta,9.014975
11,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,8.994067
12,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,Del Rey,8.936750
13,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1999,Houghton Mifflin Company,8.936750
14,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. Tolkien,2002,Houghton Mifflin,8.936750
15,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1988,Houghton Mifflin Company,8.936750
16,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,2001,Houghton Mifflin Company,8.936750
17,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1988,Houghton Mifflin,8.936750
18,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,2002,Houghton Mifflin Company,8.936750
19,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,2003,Houghton Mifflin Company,8.936750

In [66]:
df1=rating_input_df[rating_input_df['Book-Title'].str.contains('Oprah', case=False, na=False)]
df1['Book-Rating'].value_counts()

Book-Rating
7.0     1702
6.0      913
8.0      829
9.0      264
10.0     260
5.0      214
4.0       29
3.0       28
2.0       13
1.0        8
Name: count, dtype: int64

# Check Accuracy

In [63]:
# Check the accuracy for both default vs tuned method
# display(f'Accuracy, based on Root Mean Square Error, of a Tuned Model: {accuracy.rmse(svd_best_parameters_model.test(test_set), verbose=False)}')
print(f'''Accuracy, based on Root Mean Square Error, of a Model with Default Parameters:
{accuracy.rmse(svd_default_model.test(test_set), verbose=False)}''')

Accuracy, based on Root Mean Square Error, of a Model with Default Parameters:
1.3041447719825463

In [64]:
print(f'''Accuracy, based on Mean Absolute Error, of a Model with Default Parameters:
{accuracy.mae(svd_default_model.test(test_set), verbose=False)}''')

Accuracy, based on Mean Absolute Error, of a Model with Default Parameters:
0.9522857634201722